CREATE TABLE IF NOT EXISTS DATA_HORA_AUTORIZACAO (
        id_autorizacao INT AUTO_INCREMENT PRIMARY KEY,
        data_hora_autorizado DATETIME
);

CREATE TABLE IF NOT EXISTS STATUS (
        id INT AUTO_INCREMENT PRIMARY KEY,
        DESCRICAO VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS UNIDADE_PENAL (
        ID_UNIDADE_PENAL INT AUTO_INCREMENT PRIMARY KEY,
        DESCRICAO VARCHAR(255),
        NOME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PESSOA (
    ID_PESSOA BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    CPF VARCHAR(14) UNIQUE,
    DATA_NASCIMENTO DATE
);

CREATE TABLE IF NOT EXISTS CUSTODIADO (
    ID_CUSTODIADO BIGINT PRIMARY KEY,
    NUMERO_PROTUARIO VARCHAR(255),
    VULGO VARCHAR(255),
    ID_UNIDADE_PENAL BIGINT,
    FOREIGN KEY (ID_CUSTODIADO) REFERENCES PESSOA(ID_PESSOA),
    FOREIGN KEY (ID_UNIDADE_PENAL) REFERENCES UNIDADE_PENAL(ID_UNIDADE_PENAL)
);

CREATE TABLE IF NOT EXISTS VISITANTE (
    ID_VISITANTE BIGINT PRIMARY KEY,
    SENHA_ONLINE VARCHAR(255),
    FOREIGN KEY (ID_VISITANTE) REFERENCES PESSOA(ID_PESSOA)
);

INSERT INTO data_hora_autorizacao (data_hora_autorizado) VALUES ('2025-04-05 08:00:00');
INSERT INTO data_hora_autorizacao (data_hora_autorizado) VALUES ('2025-04-05 10:00:00');
INSERT INTO data_hora_autorizacao (data_hora_autorizado) VALUES ('2025-04-05 12:00:00');

INSERT INTO data_hora_autorizacao (data_hora_autorizado) VALUES ('2025-04-10 08:00:00');
INSERT INTO data_hora_autorizacao (data_hora_autorizado) VALUES ('2025-04-10 10:00:00');
INSERT INTO data_hora_autorizacao (data_hora_autorizado) VALUES ('2025-04-10 12:00:00');

INSERT INTO data_hora_autorizacao (data_hora_autorizado) VALUES ('2025-04-15 08:00:00');
INSERT INTO data_hora_autorizacao (data_hora_autorizado) VALUES ('2025-04-15 10:00:00');
INSERT INTO data_hora_autorizacao (data_hora_autorizado) VALUES ('2025-04-15 12:00:00');

INSERT INTO data_hora_autorizacao (data_hora_autorizado) VALUES ('2025-04-20 08:00:00');
INSERT INTO data_hora_autorizacao (data_hora_autorizado) VALUES ('2025-04-20 10:00:00');
INSERT INTO data_hora_autorizacao (data_hora_autorizado) VALUES ('2025-04-20 12:00:00');


INSERT INTO STATUS (DESCRICAO) VALUES ('AGENDADO');
INSERT INTO STATUS (DESCRICAO) VALUES ('CANCELADO');
INSERT INTO STATUS (DESCRICAO) VALUES ('REALIZADO');
INSERT INTO STATUS (DESCRICAO) VALUES ('SUSPENSO');

INSERT INTO UNIDADE_PENAL (DESCRICAO, NOME) VALUES ('PDF I', 'PENITENCIARIO DO DISTRITO FEDERAL I');
INSERT INTO UNIDADE_PENAL (DESCRICAO, NOME) VALUES ('PDF II', 'PENITENCIARIO DO DISTRITO FEDERAL II');
INSERT INTO UNIDADE_PENAL (DESCRICAO, NOME) VALUES ('PDF IV', 'PENITENCIARIO DO DISTRITO FEDERAL IV');
INSERT INTO UNIDADE_PENAL (DESCRICAO, NOME) VALUES ('CIR', 'CENTRO DE INTERNAMENTO E REEDUCACAO');
INSERT INTO UNIDADE_PENAL (DESCRICAO, NOME) VALUES ('CDP', 'CENTRO DE DETENCAO PROVISORIA');
INSERT INTO UNIDADE_PENAL (DESCRICAO, NOME) VALUES ('PFDF', 'PENITENCIARIA FEMININA DO DISTRITO FEDERAL');
INSERT INTO UNIDADE_PENAL (DESCRICAO, NOME) VALUES ('CPP', 'CENTRO DE PROGRESSAO PENITENCIARIA');


INSERT INTO PESSOA (NOME, CPF, DATA_NASCIMENTO)
VALUES ('CARLOS ALBERTO', '111.222.393-44', '1980-05-15');
SET @ID_PESSOA1 = (SELECT MAX(ID_PESSOA) FROM PESSOA);
INSERT INTO VISITANTE (ID_VISITANTE, SENHA_ONLINE)
VALUES (@ID_PESSOA1, 'AbCd@123');


INSERT INTO PESSOA (NOME, CPF, DATA_NASCIMENTO)
VALUES ('ANA PAULA', '555.666.777-88', '1992-12-01');
SET @ID_PESSOA2 = (SELECT MAX(ID_PESSOA) FROM PESSOA);
INSERT INTO VISITANTE (ID_VISITANTE, SENHA_ONLINE)
VALUES (@ID_PESSOA2, 'XyZz!456');


INSERT INTO PESSOA (NOME, CPF, DATA_NASCIMENTO)
VALUES ('RODRIGO SILVA', '999.000.111-22', '1988-08-20');
SET @ID_PESSOA3 = (SELECT MAX(ID_PESSOA) FROM PESSOA);
INSERT INTO VISITANTE (ID_VISITANTE, SENHA_ONLINE)
VALUES (@ID_PESSOA3, 'P@SsWOrd');


INSERT INTO PESSOA (NOME, CPF, DATA_NASCIMENTO)
VALUES ('MARIANA GOMES', '333.444.555-66', '1995-03-10');
SET @ID_PESSOA4 = (SELECT MAX(ID_PESSOA) FROM PESSOA);
INSERT INTO VISITANTE (ID_VISITANTE, SENHA_ONLINE)
VALUES (@ID_PESSOA4, 'sTr0nG#7');


INSERT INTO PESSOA (NOME, CPF, DATA_NASCIMENTO)
VALUES ('LUCAS FERREIRA', '777.888.999-00', '2001-06-25');
SET @ID_PESSOA5 = (SELECT MAX(ID_PESSOA) FROM PESSOA);
INSERT INTO VISITANTE (ID_VISITANTE, SENHA_ONLINE)
VALUES (@ID_PESSOA5, 'mY$ecRet');


INSERT INTO PESSOA (NOME, CPF, DATA_NASCIMENTO)
VALUES ('RICARDO ALMEIDA', '123.456.789-01', '1985-07-20');
SET @ID_CUSTODIADO1 = (SELECT MAX(ID_PESSOA) FROM PESSOA);
INSERT INTO CUSTODIADO (ID_CUSTODIADO, NUMERO_PROTUARIO, VULGO, ID_UNIDADE_PENAL)
VALUES (@ID_CUSTODIADO1, '67890', 'RICK', 1);


INSERT INTO PESSOA (NOME, CPF, DATA_NASCIMENTO)
VALUES ('FERNANDO SOUZA', '987.654.321-02', '1990-03-15');
SET @ID_CUSTODIADO2 = (SELECT MAX(ID_PESSOA) FROM PESSOA);
INSERT INTO CUSTODIADO (ID_CUSTODIADO, NUMERO_PROTUARIO, VULGO, ID_UNIDADE_PENAL)
VALUES (@ID_CUSTODIADO2, '12345678', 'NANDO', 2);


INSERT INTO PESSOA (NOME, CPF, DATA_NASCIMENTO)
VALUES ('GABRIEL RODRIGUES', '456.789.012-03', '2000-11-28');
SET @ID_CUSTODIADO3 = (SELECT MAX(ID_PESSOA) FROM PESSOA);
INSERT INTO CUSTODIADO (ID_CUSTODIADO, NUMERO_PROTUARIO, VULGO, ID_UNIDADE_PENAL)
VALUES (@ID_CUSTODIADO3, '98765', 'GABI', 3);


INSERT INTO PESSOA (NOME, CPF, DATA_NASCIMENTO)
VALUES ('LEONARDO OLIVEIRA', '789.012.345-04', '1978-01-05');
SET @ID_CUSTODIADO4 = (SELECT MAX(ID_PESSOA) FROM PESSOA);
INSERT INTO CUSTODIADO (ID_CUSTODIADO, NUMERO_PROTUARIO, VULGO, ID_UNIDADE_PENAL)
VALUES (@ID_CUSTODIADO4, '543216', 'LEO', 4);


INSERT INTO PESSOA (NOME, CPF, DATA_NASCIMENTO)
VALUES ('MATHEUS COSTA', '012.345.678-05', '1995-09-10');
SET @ID_CUSTODIADO5 = (SELECT MAX(ID_PESSOA) FROM PESSOA);
INSERT INTO CUSTODIADO (ID_CUSTODIADO, NUMERO_PROTUARIO, VULGO, ID_UNIDADE_PENAL)
VALUES (@ID_CUSTODIADO5, '1234567', 'MAT', 5);