CREATE TABLE IF NOT EXISTS DATA_HORA_AUTORIZACAO (
        id_autorizacao INT AUTO_INCREMENT PRIMARY KEY,
        data_hora_autorizado DATETIME
);

CREATE TABLE IF NOT EXISTS STATUS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(25) NOT NULL
    );